[package]
name = "gn-language-server"
description = "A language server for GN, the build configuration language used in Chromium, Fuchsia, and other projects"
version = "1.9.0"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/google/gn-language-server"
exclude = [
    ".github",
    "docs",
    "testdata",
    "vscode-gn",
]

[dependencies]
either = "1.13.0"
futures = "0.3.31"
itertools = "0.14.0"
normalize-path = "0.2.1"
pest = "2.7.15"
pest_derive = "2.7.15"
serde = "1.0.217"
serde_json = "1.0.134"
thiserror = "2.0.12"
tokio = { version = "1.47.0", features = ["io-std", "io-util", "macros", "process", "rt-multi-thread", "sync"] }
tower-lsp = "0.20.0"
walkdir = "2.5.0"
which = "7.0.2"

[dev-dependencies]
tempfile = "3.19.1"

[build-dependencies]
cc = "1.2.7"
